# Generated by Django 4.2.2 on 2023-06-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='professors',
            new_name='professor',
        ),
        migrations.RenameModel(
            old_name='students',
            new_name='student',
        ),
    ]
