# Generated by Django 4.2.2 on 2023-06-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_professors_professor_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='price',
        ),
    ]
