# Generated by Django 4.2.2 on 2023-06-10 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_professor_students_student_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='professor',
            new_name='professors',
        ),
    ]
